spring:
  application:
    name: "Trajectory-Processor Server API"
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

---

spring:
  config:
    activate:
      on-profile: dev

---
